### ISSUE TITLE
上传列表的简单实现

### ISSUE THREAD

**Issue by deng-rui** [wtbdev/Rukkit#1]
[domo.zip](https://github.com/wtbdev/Rukkit/files/4492904/domo.zip)
这只是一个简单的实现(单文件 GIT不支持JAVA上传)
可在列表查询到
祝项目好运 :+1:

**Comment by wtbdev** [comment]
已经加入，在publisher-branch里

**Comment by yiyungent** [comment]
> [domo.zip](https://github.com/wtbdev/Rukkit/files/4492904/domo.zip)
> 这只是一个简单的实现(单文件 GIT不支持JAVA上传)
> 可在列表查询到
> 祝项目好运 👍

`Not Found` 了，大佬，再上传一份？

**Comment by deng-rui** [comment]
> > [domo.zip](https://github.com/wtbdev/Rukkit/files/4492904/domo.zip)
> > 这只是一个简单的实现(单文件 GIT不支持JAVA上传)
> > 可在列表查询到
> > 祝项目好运 👍
> 
> `Not Found` 了，大佬，再上传一份？

很遗憾 没有备份
