### ISSUE TITLE
Packet.bytes 溢出

### ISSUE THREAD

**Issue by deng-rui** [wtbdev/Rukkit#3]
请验证Packet.bytes的大小
若发送虚假包 则会导致Server Over

**Comment by deng-rui** [comment]
DataInputStream in = new DataInputStream(socket.getInputStream());
int size = in.readInt();
/*
if (size .....
*/
Packet packet = new Packet(in.readInt());
packet.bytes = new byte[size];
SIZE需要检查

**Comment by wtbdev** [comment]
Rukkit的旧版本已经进入停止开发周期了，所有issue将会被关闭。这个问题新版本已经被解决
