### ISSUE TITLE
How to compile? 

### ISSUE THREAD

**Issue by byzp** [wtbdev/Rukkit#7]
(ubuntu 21.10 arm，openjdk-8-jdk-headless)
ubuntu@ubuntu:~/r$ ./gradlew

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/r/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'Rukkit'.
> Supplied String module notation 'netty' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by wtbdev** [comment]
this problem is in build.gradle.I have already fixed in latest commits.
