### ISSUE TITLE
/ 

### ISSUE THREAD

**Issue by byzp** [wtbdev/Rukkit#8]
(ubuntu server 21.10 arm,openjdk-16-jdk-headless)
ubuntu@ubuntu:~/rw2$ ls
Rukkit-0.8.2-dev.jar  libs  start.bat  start.sh
ubuntu@ubuntu:~/rw2$ ./start.sh
Error: Could not find or load main class cn.rukkit.RukkitLauncher
Caused by: java.lang.ClassNotFoundException: cn.rukkit.RukkitLauncher

**Comment by wtbdev** [comment]
using
`java -cp libs/*:Rukkit-0.8.2-dev.jar cn.rukkit.RukkitLauncher
`
starter script have some problems.I'll check it.

**Comment by byzp** [comment]
ubuntu@ubuntu:~/rw2$ java -cp libs/*:Rukkit-0.8.2-dev.jar cn.rukkit.RukkitLauncher
Error: Unable to initialize main class cn.rukkit.RukkitLauncher
Caused by: java.lang.NoClassDefFoundError: io/netty/util/internal/logging/InternalLoggerFactory

**Comment by wtbdev** [comment]
check libs dir.it should have all dependences include netty,snakeyaml,fastjson and so on.

**Comment by byzp** [comment]
ubuntu@ubuntu:~/rw2$ ls libs
fastjson-1.2.37.jar        logback-core-1.2.3.jar      slf4j-api-1.7.30.jar
logback-classic-1.2.3.jar  netty-all-4.0.56.Final.jar  snakeyaml-1.25.1.jar
ubuntu@ubuntu:~/rw2$ java -cp libs/*:Rukkit-0.8.2-dev.jar cn.rukkit.RukkitLauncher
Error: Unable to initialize main class cn.rukkit.RukkitLauncher
Caused by: java.lang.NoClassDefFoundError: io/netty/util/internal/logging/InternalLoggerFactory

**Comment by byzp** [comment]
文件传递时出错，现在问题解决了，谢谢大佬ღ( ´･ᴗ･` )
